services:
  cultanime:
    build: .
    container_name: cultanime
    env_file:
      - .env
    environment:
      - TZ=Etc/UTC
    volumes:
      # SQLite database and config
      - /mnt/Fast_SSD/cultanime_data:/app/data
      # Anime media folder mounted read-only
      - /mnt/Storage_HDD/media/anime:/anime:ro
    ports:
      - 3000:3000
    restart: unless-stopped